version: '3.1'
services:
    php_api:
        build: ../Docker
        volumes:
            - ../Docker/htdocs:/var/www/html/
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: SommerCamp
            MYSQL_USER: SommerCamp
            MYSQL_PASSWORD: Sommer2023
        volumes:
            - ../Docker/mariadb:/var/lib/mysql/
            - ../Docker/DB.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - 3306:3306
        expose:
            # Für DEV, muss später entfernt werden!
            - 3306
    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mariadb
        environment:
            PMA_HOSTS: mariadb
            PMA_PORTS: 3306
            MYSQL_ROOT_PASSWORD: 1234
            PMA_ABSOLUTE_URI: /phpmyadmin/
    web:
        image: httpd
        volumes:
            - "../frontend:/usr/local/apache2/htdocs/"
    proxy:
        image: nginx
        ports:
            - 80:80
        expose:
            - 80
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - web
            - phpmyadmin
            - php_api
volumes:
    phypmyadmin:
